sudo: false
language: python
python:
  - "2.7"
  - "3.3"
  - "3.4"
  - "3.5"
# test command
install:
 - python setup.py install
script:
 - python setup.py flake8
 - python setup.py test
 - cmark.py CommonMark/test/test.md
 - cmark.py CommonMark/test/test.md -a
 - cmark.py CommonMark/test/test.md -aj
