sudo: false
language: python
python:
  - "2.6"
  - "2.7"
  - "3.3"
  - "3.4"
  - "3.5"
# test command
install:
 - python setup.py install
script:
 - python setup.py flake8
 - python -m unittest CommonMark.tests.unit_tests
 - python setup.py test
 - cmark CommonMark/tests/test.md
 - cmark CommonMark/tests/test.md -a
 - cmark CommonMark/tests/test.md -aj
